### ISSUE TITLE
ClassNotFoundError in Contao 4.13

### ISSUE THREAD

**Issue by patrickjDE** [1up-lab/contao-ical-export#14]
### Bug Report

Using the frontend module in a Contao 4.13 installation throws a ClassNotFoundError in https://github.com/1up-lab/contao-ical-export/blob/master/src/Module/ICalExport.php#L27

> Attempted to load class "Utf8" from namespace "Patchwork".
> Did you forget a "use" statement for another namespace?

**Comment by bytehead** [comment]
`2.1.1` has been released.
