### ISSUE TITLE
No description set in iCal files

### ISSUE THREAD

**Issue by Kahmoon** [1up-lab/contao-ical-export#16]
### Bug Report

No Description is set in iCal files.

<img width="1136" alt="Bildschirmfoto 2022-05-06 um 08 50 01" src="https://user-images.githubusercontent.com/6390770/167081496-ea4b8728-28e1-4daa-8e65-d486d5afbd2b.png">

![SCR-20220506-c9z](https://user-images.githubusercontent.com/6390770/167081538-ca7d9c63-f0ba-4dda-b002-9b221adf880d.png)

```
BEGIN:VCALENDAR
PRODID:-//eluceo/ical//2.0/EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:2e836f9f87b83e6119f6685d2edfa909
DTSTAMP:20220506T065008Z
SUMMARY:Externes Revier (M-2205)
DESCRIPTION:
URL:https://dev.xxx.de/preview.php/intern/termin/externes-r
 evier-m-2205-14-05-2022-9339.html
DTSTART:20220514T080000
DTEND:20220514T130000
LOCATION:Hauptstraße 1\, 85254 Sulzemoos
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART:20220514T080000
TZNAME:CEST
TZOFFSETTO:+0200
TZOFFSETFROM:+0200
END:DAYLIGHT
END:VTIMEZONE
END:VCALENDAR
```

Contao 4.13.4
iCal: dev-fix/timezone

**Comment by bytehead** [comment]
What is the value stored in your database?

**Comment by Kahmoon** [comment]
WTF...its empty!?

<img width="993" alt="Bildschirmfoto 2022-05-06 um 09 07 08" src="https://user-images.githubusercontent.com/6390770/167083789-8fa2d2a7-fecf-4173-94c3-e712f1b0572e.png">


But where is teaser stored? I cannot find it

**Comment by bytehead** [comment]
Ah there we go :) I don't know. Any other extension?

**Comment by Kahmoon** [comment]
Thats weird...i prod site its working. Sorry!

```
BEGIN:VCALENDAR
PRODID:-//eluceo/ical//2.0/EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:0536183ce5127a46cd38d3a245d8528d
DTSTAMP:20220506T071330Z
SUMMARY:Abendansitz Windachtal (diverse Kurse)
DESCRIPTION:test
URL:https://www.xxx.de/preview.php/intern/termin/abendansit
 z-windachtal-diverse-kurse-06-05-2022-9391.html
DTSTART:20220506T173000
DTEND:20220506T220000
LOCATION:Siehe Location im Text
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART:20220506T173000
TZNAME:CEST
TZOFFSETTO:+0200
TZOFFSETFROM:+0200
END:DAYLIGHT
END:VTIMEZONE
END:VCALENDAR
```
