### ISSUE TITLE
Compability Contao 4

### ISSUE THREAD

**Issue by Jaaaan** [1up-lab/contao-ical-export#2]
In the new Contao Manager, the extension is already displayed in the catalog, but an installation always fails due to a missing share for Contao 4.
Would it be possible to release this release for Contao 4?

Information about the necessary adjustments: https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md

**Comment by bytehead** [comment]
Fixed in 95bbd66. Also released [`1.2.0`](https://github.com/1up-lab/contao-ical-export/releases/tag/1.2.0). Thanks for reporting!
