### ISSUE TITLE
No downloadlink is displayed - Contao 4.4.8

### ISSUE THREAD

**Issue by jammon88** [1up-lab/contao-ical-export#3]
Hi there

I've created a modul with one calender and added the modul to a page, but there is no download link displayed. The link to the page is the following: https://www.feuerwehr-arbon.ch/kader.html. We use Contao 4.4.8. I've installed the plugin via contao manager.

Regards Roman

**Comment by bytehead** [comment]
Hi @jammon88 

Thanks for reporting. Sadly, the extension is not contao-manager ready yet (will not be loaded by the manager right now). I'll provide an update probably this week and it will be act like expected.

**Comment by bytehead** [comment]
See #4

**Comment by bytehead** [comment]
I've just released version `2.0.0`, should be installable now via contao manager.

Hint: you have to place the iCal-export module on the reader/detail page of an event (e.g: https://www.feuerwehr-arbon.ch/eventreader/kader.html).
