### ISSUE TITLE
Keine Ausgabe im Frontend

### ISSUE THREAD

**Issue by planepix** [1up-lab/contao-ical-export#6]
Hallo Dave,

ich habe eure Erweiterung unter einer 4.4.12 installiert.
Dann ein Frontendmodul erstellt und das in eine Seite als CE eingebunden.

Keine Ausgabe der beiden angeklickten Eventarchive im Frontend; auch im Code wird nichts ausgegeben.

Benötigt es noch anderer Einstellungen, die ich übersehen habe, oder ist es, trotzdem es fehlerfrei installiert werden konnte, mit der 4.4.12 aktuell nicht einsetzbar?

Danke und Grüße
Thomas

**Comment by bytehead** [comment]
Hallo Thomas

Die Erweiterung gibt bis jetzt nur einen Download-Link aus, wenn du auf einem Detaileintrag bist.
Beispiel: https://www.lit-z.ch/programm/event/max-kueng-die-rettung-der-dinge.html

Der Feature-Request für den Export vom ganzen Eventarchiv ist noch hängig: #5.

**Comment by bytehead** [comment]
See #5

**Comment by planepix** [comment]
Danke Dave, auf Detailseite ! Bingo. Das passt völlig.
