### ISSUE TITLE
iCal Download does not work when URL contains Parameters 

### ISSUE THREAD

**Issue by Kahmoon** [1up-lab/contao-ical-export#7]
The default detail link of the eventreader contains URL parameters. Then the download of the ical element does not work.

When you set "no parameters" in calendar module it works fine.

For listing module there is no such option...you have to clean up the link via regular expressions in template.

**Comment by bytehead** [comment]
I cannot reproduce this in the offical demo on my local machine.
My eventreader module doesn't even have a setting "no parameters":
![bildschirmfoto 2019-02-08 um 19 00 01](https://user-images.githubusercontent.com/754921/52496695-51fb5e00-2bd4-11e9-8bef-b9303fb44fae.png)

Can you give some more information to reproduce the situation?

**Comment by Kahmoon** [comment]
This setting is in module calendar,not reader. See right bottom corner of the screenshot. And it seems to be an option from calendar_extend at the end.

<a href="https://ibb.co/kxd1HZ4"><img src="https://i.ibb.co/ZVZmL9B/Bildschirmfoto-2019-02-08-um-19-20-14.png" alt="Bildschirmfoto-2019-02-08-um-19-20-14" border="0"></a>

In Contao Demo (https://demo.contao.org/en/events.html?month=201905) the link to an event got no parameters at all....thats fine. Parameters seems to be set via calendar_extend

On listing templates you have to remove it via regexp

We can close this issue ;-). Sorry

**Comment by bytehead** [comment]
I'll check, maybe we can fix this anyway.

**Comment by Kahmoon** [comment]
The link in my listing & reader is like. 
 myfolder/test-8-2-kopie.html?**day=20190208&times=1549580400,1549666799**

The downloadlink from your module becomes
myfolder/test-8-2-kopie.html?day=20190208&times=1549580400,1549666799?ics

So we have two beginnings of parameter "?"

**Comment by bytehead** [comment]
Version `2.0.2` fixes this, thanks for reporting!
