### ISSUE TITLE
Special characters in event titel are broken

### ISSUE THREAD

**Issue by Kahmoon** [1up-lab/contao-ical-export#8]
When event titles contains special characters they are broken in calendar e.g. Oulook

`Test 8.2 (Kurs A)`

becomes

`Test 8.2 &#40;Kurs A&#41;`

There was a similar problem at notifictaion_center
https://github.com/codefog/contao-events_subscriptions/issues/13

This could be fixed probably pretty easy

Frank

**Comment by bytehead** [comment]
Just released `2.0.1`, thanks for reporting.
